# Generated by Django 5.2.7 on 2025-11-16 17:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis_raster'),
        migrations.CreateModel(
            name='NDVILayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('satellite', models.CharField(max_length=32)),
                ('image', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField()),
                ('distance', models.FloatField()),
                ('ascend', models.FloatField()),
                ('descend', models.FloatField()),
                ('instructions', models.JSONField()),
                ('request_time', models.DateField()),
                ('route', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('departure', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
