# Generated by Django 5.2.7 on 2025-12-07 21:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_route_request_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('municipality', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=24)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
