# Generated by Django 5.2.7 on 2025-12-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ndvi_count',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
