# Generated by Django 5.2.7 on 2025-12-10 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_route_ndvi_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shadow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('time', models.DateTimeField()),
                ('season', models.CharField(max_length=12)),
            ],
        ),
    ]
