# Generated by Django 5.2.7 on 2025-12-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shadow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shadow',
            name='time',
            field=models.TimeField(),
        ),
    ]
